name: Publish to PyPI

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          python -m pip install poetry 
          pip install poetry setuptools setuptools_scm wheel twine poetry-dynamic-versioning

      - name: Install project dependencies
        run: poetry install

      - name: Build package
        run: |
          poetry self add poetry-dynamic-versioning
          poetry build

      - name: Publish package to PyPI
        run: |
          twine upload --repository pypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
